// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace iBabyShapes {
    
    
    // Base type probably should be MonoTouch.UIKit.UIViewController or subclass
    [MonoTouch.Foundation.Register("DrawingViewController")]
    public partial class DrawingViewController {
        
        private DrawingView __mt_view;
        
        #pragma warning disable 0169
        [MonoTouch.Foundation.Connect("view")]
        private DrawingView view {
            get {
                this.__mt_view = ((DrawingView)(this.GetNativeField("view")));
                return this.__mt_view;
            }
            set {
                this.__mt_view = value;
                this.SetNativeField("view", value);
            }
        }
    }
}
